server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:delevel}

  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_SCHEMA};TrustServerCertificate=True;
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
